
using ProtoBuf;

namespace SteamKit.Client.Model.GC.CS2
{
    [ProtoContract()]
    public enum GCClientLauncherType
    {
        GCClientLauncherType_DEFAULT = 0,
        GCClientLauncherType_PERFECTWORLD = 1,
        GCClientLauncherType_STEAMCHINA = 2,
        GCClientLauncherType_SOURCE2 = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EInitSystemResult
    {
        k_EInitSystemResult_Invalid = 0,
        k_EInitSystemResult_Success = 1,
        k_EInitSystemResult_None = 2,
        k_EInitSystemResult_NotFound = 3,
        k_EInitSystemResult_Existing = 4,
        k_EInitSystemResult_FailedOpen = 5,
        k_EInitSystemResult_Mismatch = 6,
        k_EInitSystemResult_FailedInit = 7,
        k_EInitSystemResult_Max = 8,
    }

    [ProtoContract()]
    public enum EGCSystemMsg
    {
        k_EGCMsgInvalid = 0,
        k_EGCMsgMulti = 1,
        k_EGCMsgGenericReply = 10,
        k_EGCMsgSystemBase = 50,
        k_EGCMsgAchievementAwarded = 51,
        k_EGCMsgConCommand = 52,
        k_EGCMsgStartPlaying = 53,
        k_EGCMsgStopPlaying = 54,
        k_EGCMsgStartGameserver = 55,
        k_EGCMsgStopGameserver = 56,
        k_EGCMsgWGRequest = 57,
        k_EGCMsgWGResponse = 58,
        k_EGCMsgGetUserGameStatsSchema = 59,
        k_EGCMsgGetUserGameStatsSchemaResponse = 60,
        k_EGCMsgGetUserStatsDEPRECATED = 61,
        k_EGCMsgGetUserStatsResponse = 62,
        k_EGCMsgAppInfoUpdated = 63,
        k_EGCMsgValidateSession = 64,
        k_EGCMsgValidateSessionResponse = 65,
        k_EGCMsgLookupAccountFromInput = 66,
        k_EGCMsgSendHTTPRequest = 67,
        k_EGCMsgSendHTTPRequestResponse = 68,
        k_EGCMsgPreTestSetup = 69,
        k_EGCMsgRecordSupportAction = 70,
        k_EGCMsgGetAccountDetails_DEPRECATED = 71,
        k_EGCMsgReceiveInterAppMessage = 73,
        k_EGCMsgFindAccounts = 74,
        k_EGCMsgPostAlert = 75,
        k_EGCMsgGetLicenses = 76,
        k_EGCMsgGetUserStats = 77,
        k_EGCMsgGetCommands = 78,
        k_EGCMsgGetCommandsResponse = 79,
        k_EGCMsgAddFreeLicense = 80,
        k_EGCMsgAddFreeLicenseResponse = 81,
        k_EGCMsgGetIPLocation = 82,
        k_EGCMsgGetIPLocationResponse = 83,
        k_EGCMsgSystemStatsSchema = 84,
        k_EGCMsgGetSystemStats = 85,
        k_EGCMsgGetSystemStatsResponse = 86,
        k_EGCMsgSendEmail = 87,
        k_EGCMsgSendEmailResponse = 88,
        k_EGCMsgGetEmailTemplate = 89,
        k_EGCMsgGetEmailTemplateResponse = 90,
        k_EGCMsgGrantGuestPass = 91,
        k_EGCMsgGrantGuestPassResponse = 92,
        k_EGCMsgGetAccountDetails = 93,
        k_EGCMsgGetAccountDetailsResponse = 94,
        k_EGCMsgGetPersonaNames = 95,
        k_EGCMsgGetPersonaNamesResponse = 96,
        k_EGCMsgMultiplexMsg = 97,
        k_EGCMsgMultiplexMsgResponse = 98,
        k_EGCMsgWebAPIRegisterInterfaces = 101,
        k_EGCMsgWebAPIJobRequest = 102,
        k_EGCMsgWebAPIJobRequestHttpResponse = 104,
        k_EGCMsgWebAPIJobRequestForwardResponse = 105,
        k_EGCMsgMemCachedGet = 200,
        k_EGCMsgMemCachedGetResponse = 201,
        k_EGCMsgMemCachedSet = 202,
        k_EGCMsgMemCachedDelete = 203,
        k_EGCMsgMemCachedStats = 204,
        k_EGCMsgMemCachedStatsResponse = 205,
        k_EGCMsgMasterSetDirectory = 220,
        k_EGCMsgMasterSetDirectoryResponse = 221,
        k_EGCMsgMasterSetWebAPIRouting = 222,
        k_EGCMsgMasterSetWebAPIRoutingResponse = 223,
        k_EGCMsgMasterSetClientMsgRouting = 224,
        k_EGCMsgMasterSetClientMsgRoutingResponse = 225,
        k_EGCMsgSetOptions = 226,
        k_EGCMsgSetOptionsResponse = 227,
        k_EGCMsgSystemBase2 = 500,
        k_EGCMsgGetPurchaseTrustStatus = 501,
        k_EGCMsgGetPurchaseTrustStatusResponse = 502,
        k_EGCMsgUpdateSession = 503,
        k_EGCMsgGCAccountVacStatusChange = 504,
        k_EGCMsgCheckFriendship = 505,
        k_EGCMsgCheckFriendshipResponse = 506,
        k_EGCMsgGetPartnerAccountLink = 507,
        k_EGCMsgGetPartnerAccountLinkResponse = 508,
        k_EGCMsgDPPartnerMicroTxns = 512,
        k_EGCMsgDPPartnerMicroTxnsResponse = 513,
        k_EGCMsgVacVerificationChange = 518,
        k_EGCMsgAccountPhoneNumberChange = 519,
        k_EGCMsgInviteUserToLobby = 523,
        k_EGCMsgGetGamePersonalDataCategoriesRequest = 524,
        k_EGCMsgGetGamePersonalDataCategoriesResponse = 525,
        k_EGCMsgGetGamePersonalDataEntriesRequest = 526,
        k_EGCMsgGetGamePersonalDataEntriesResponse = 527,
        k_EGCMsgTerminateGamePersonalDataEntriesRequest = 528,
        k_EGCMsgTerminateGamePersonalDataEntriesResponse = 529,
        k_EGCMsgRecurringSubscriptionStatusChange = 530,
        k_EGCMsgDirectServiceMethod = 531,
        k_EGCMsgDirectServiceMethodResponse = 532,
    }

    [ProtoContract()]
    public enum ESOMsg
    {
        k_ESOMsg_Create = 21,
        k_ESOMsg_Update = 22,
        k_ESOMsg_Destroy = 23,
        k_ESOMsg_CacheSubscribed = 24,
        k_ESOMsg_CacheUnsubscribed = 25,
        k_ESOMsg_UpdateMultiple = 26,
        k_ESOMsg_CacheSubscriptionCheck = 27,
        k_ESOMsg_CacheSubscriptionRefresh = 28,
    }

    [ProtoContract]
    public enum EGCBaseClientMsg
    {
        k_EMsgGCClientWelcome = 4004,
        k_EMsgGCServerWelcome = 4005,
        k_EMsgGCClientHello = 4006,
        k_EMsgGCServerHello = 4007,
        k_EMsgGCClientConnectionStatus = 4009,
        k_EMsgGCServerConnectionStatus = 4010,
        k_EMsgGCClientHelloPartner = 4011,
        k_EMsgGCClientHelloPW = 4012,
        k_EMsgGCClientHelloR2 = 4013,
        k_EMsgGCClientHelloR3 = 4014,
        k_EMsgGCClientHelloR4 = 4015,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EGCBaseMsg
    {
        k_EMsgGCSystemMessage = 4001,
        k_EMsgGCReplicateConVars = 4002,
        k_EMsgGCConVarUpdated = 4003,
        k_EMsgGCInQueue = 4008,
        k_EMsgGCInviteToParty = 4501,
        k_EMsgGCInvitationCreated = 4502,
        k_EMsgGCPartyInviteResponse = 4503,
        k_EMsgGCKickFromParty = 4504,
        k_EMsgGCLeaveParty = 4505,
        k_EMsgGCServerAvailable = 4506,
        k_EMsgGCClientConnectToServer = 4507,
        k_EMsgGCGameServerInfo = 4508,
        k_EMsgGCError = 4509,
        k_EMsgGCReplay_UploadedToYouTube = 4510,
        k_EMsgGCLANServerAvailable = 4511,
    }

    [ProtoContract]
    public enum ECsgoGCMsg
    {
        k_EMsgGCCStrike15_v2_Base = 9100,
        k_EMsgGCCStrike15_v2_MatchmakingStart = 9101,
        k_EMsgGCCStrike15_v2_MatchmakingStop = 9102,
        k_EMsgGCCStrike15_v2_MatchmakingClient2ServerPing = 9103,
        k_EMsgGCCStrike15_v2_MatchmakingGC2ClientUpdate = 9104,
        k_EMsgGCCStrike15_v2_MatchmakingServerReservationResponse = 9106,
        k_EMsgGCCStrike15_v2_MatchmakingGC2ClientReserve = 9107,
        k_EMsgGCCStrike15_v2_MatchmakingClient2GCHello = 9109,
        k_EMsgGCCStrike15_v2_MatchmakingGC2ClientHello = 9110,
        k_EMsgGCCStrike15_v2_MatchmakingGC2ClientAbandon = 9112,
        k_EMsgGCCStrike15_v2_MatchmakingGCOperationalStats = 9115,
        k_EMsgGCCStrike15_v2_MatchmakingOperator2GCBlogUpdate = 9117,
        k_EMsgGCCStrike15_v2_ServerNotificationForUserPenalty = 9118,
        k_EMsgGCCStrike15_v2_ClientReportPlayer = 9119,
        k_EMsgGCCStrike15_v2_ClientReportServer = 9120,
        k_EMsgGCCStrike15_v2_ClientCommendPlayer = 9121,
        k_EMsgGCCStrike15_v2_ClientReportResponse = 9122,
        k_EMsgGCCStrike15_v2_ClientCommendPlayerQuery = 9123,
        k_EMsgGCCStrike15_v2_ClientCommendPlayerQueryResponse = 9124,
        k_EMsgGCCStrike15_v2_WatchInfoUsers = 9126,
        k_EMsgGCCStrike15_v2_ClientRequestPlayersProfile = 9127,
        k_EMsgGCCStrike15_v2_PlayersProfile = 9128,
        k_EMsgGCCStrike15_v2_PlayerOverwatchCaseUpdate = 9131,
        k_EMsgGCCStrike15_v2_PlayerOverwatchCaseAssignment = 9132,
        k_EMsgGCCStrike15_v2_PlayerOverwatchCaseStatus = 9133,
        k_EMsgGCCStrike15_v2_GC2ClientTextMsg = 9134,
        k_EMsgGCCStrike15_v2_Client2GCTextMsg = 9135,
        k_EMsgGCCStrike15_v2_MatchEndRunRewardDrops = 9136,
        k_EMsgGCCStrike15_v2_MatchEndRewardDropsNotification = 9137,
        k_EMsgGCCStrike15_v2_ClientRequestWatchInfoFriends2 = 9138,
        k_EMsgGCCStrike15_v2_MatchList = 9139,
        k_EMsgGCCStrike15_v2_MatchListRequestCurrentLiveGames = 9140,
        k_EMsgGCCStrike15_v2_MatchListRequestRecentUserGames = 9141,
        k_EMsgGCCStrike15_v2_GC2ServerReservationUpdate = 9142,
        k_EMsgGCCStrike15_v2_ClientVarValueNotificationInfo = 9144,
        k_EMsgGCCStrike15_v2_MatchListRequestTournamentGames = 9146,
        k_EMsgGCCStrike15_v2_MatchListRequestFullGameInfo = 9147,
        k_EMsgGCCStrike15_v2_GiftsLeaderboardRequest = 9148,
        k_EMsgGCCStrike15_v2_GiftsLeaderboardResponse = 9149,
        k_EMsgGCCStrike15_v2_ServerVarValueNotificationInfo = 9150,
        k_EMsgGCCStrike15_v2_ClientSubmitSurveyVote = 9152,
        k_EMsgGCCStrike15_v2_Server2GCClientValidate = 9153,
        k_EMsgGCCStrike15_v2_MatchListRequestLiveGameForUser = 9154,
        k_EMsgGCCStrike15_v2_Client2GCEconPreviewDataBlockRequest = 9156,
        k_EMsgGCCStrike15_v2_Client2GCEconPreviewDataBlockResponse = 9157,
        k_EMsgGCCStrike15_v2_AccountPrivacySettings = 9158,
        k_EMsgGCCStrike15_v2_SetMyActivityInfo = 9159,
        k_EMsgGCCStrike15_v2_MatchListRequestTournamentPredictions = 9160,
        k_EMsgGCCStrike15_v2_MatchListUploadTournamentPredictions = 9161,
        k_EMsgGCCStrike15_v2_DraftSummary = 9162,
        k_EMsgGCCStrike15_v2_ClientRequestJoinFriendData = 9163,
        k_EMsgGCCStrike15_v2_ClientRequestJoinServerData = 9164,
        k_EMsgGCCStrike15_v2_ClientRequestNewMission = 9165,
        k_EMsgGCCStrike15_v2_GC2ClientTournamentInfo = 9167,
        k_EMsgGC_GlobalGame_Subscribe = 9168,
        k_EMsgGC_GlobalGame_Unsubscribe = 9169,
        k_EMsgGC_GlobalGame_Play = 9170,
        k_EMsgGCCStrike15_v2_AcknowledgePenalty = 9171,
        k_EMsgGCCStrike15_v2_Client2GCRequestPrestigeCoin = 9172,
        k_EMsgGCCStrike15_v2_GC2ClientGlobalStats = 9173,
        k_EMsgGCCStrike15_v2_Client2GCStreamUnlock = 9174,
        k_EMsgGCCStrike15_v2_FantasyRequestClientData = 9175,
        k_EMsgGCCStrike15_v2_FantasyUpdateClientData = 9176,
        k_EMsgGCCStrike15_v2_GCToClientSteamdatagramTicket = 9177,
        k_EMsgGCCStrike15_v2_ClientToGCRequestTicket = 9178,
        k_EMsgGCCStrike15_v2_ClientToGCRequestElevate = 9179,
        k_EMsgGCCStrike15_v2_GlobalChat = 9180,
        k_EMsgGCCStrike15_v2_GlobalChat_Subscribe = 9181,
        k_EMsgGCCStrike15_v2_GlobalChat_Unsubscribe = 9182,
        k_EMsgGCCStrike15_v2_ClientAuthKeyCode = 9183,
        k_EMsgGCCStrike15_v2_GotvSyncPacket = 9184,
        k_EMsgGCCStrike15_v2_ClientPlayerDecalSign = 9185,
        k_EMsgGCCStrike15_v2_ClientLogonFatalError = 9187,
        k_EMsgGCCStrike15_v2_ClientPollState = 9188,
        k_EMsgGCCStrike15_v2_Party_Register = 9189,
        k_EMsgGCCStrike15_v2_Party_Unregister = 9190,
        k_EMsgGCCStrike15_v2_Party_Search = 9191,
        k_EMsgGCCStrike15_v2_Party_Invite = 9192,
        k_EMsgGCCStrike15_v2_Account_RequestCoPlays = 9193,
        k_EMsgGCCStrike15_v2_ClientGCRankUpdate = 9194,
        k_EMsgGCCStrike15_v2_ClientRequestOffers = 9195,
        k_EMsgGCCStrike15_v2_ClientAccountBalance = 9196,
        k_EMsgGCCStrike15_v2_ClientPartyJoinRelay = 9197,
        k_EMsgGCCStrike15_v2_ClientPartyWarning = 9198,
        k_EMsgGCCStrike15_v2_SetEventFavorite = 9200,
        k_EMsgGCCStrike15_v2_GetEventFavorites_Request = 9201,
        k_EMsgGCCStrike15_v2_ClientPerfReport = 9202,
        k_EMsgGCCStrike15_v2_GetEventFavorites_Response = 9203,
        k_EMsgGCCStrike15_v2_ClientRequestSouvenir = 9204,
        k_EMsgGCCStrike15_v2_ClientReportValidation = 9205,
        k_EMsgGCCStrike15_v2_GC2ClientRefuseSecureMode = 9206,
        k_EMsgGCCStrike15_v2_GC2ClientRequestValidation = 9207,
        k_EMsgGCCStrike15_v2_ClientRedeemMissionReward = 9209,
        k_EMsgGCCStrike15_ClientDeepStats = 9210,
        k_EMsgGCCStrike15_StartAgreementSessionInGame = 9211,
        k_EMsgGCCStrike15_v2_GC2ClientInitSystem = 9212,
        k_EMsgGCCStrike15_v2_GC2ClientInitSystem_Response = 9213,
        k_EMsgGCCStrike15_v2_PrivateQueues = 9214,
        k_EMsgGCCStrike15_v2_MatchListTournamentOperatorMgmt = 9215,
        k_EMsgGCCStrike15_v2_BetaEnrollment = 9217,
        k_EMsgGCCStrike15_v2_SetPlayerLeaderboardSafeName = 9218,
        k_EMsgGCCStrike15_v2_ClientRedeemFreeReward = 9219,
        k_EMsgGCCStrike15_v2_ClientNetworkConfig = 9220,
        k_EMsgGCCStrike15_v2_GC2ClientNotifyXPShop = 9221,
        k_EMsgGCCStrike15_v2_Client2GcAckXPShopTracks = 9222,
        k_EMsgGCCStrike15_v2_MatchmakingGC2ClientSearchStats = 9223,
        k_EMsgGCCStrike15_v2_PremierSeasonSummary = 9224,
        k_EMsgGCCStrike15_v2_RequestRecurringMissionSchedule = 9225,
        k_EMsgGCCStrike15_v2_RecurringMissionSchema = 9226,
    }

    [ProtoContract()]
    public enum GCConnectionStatus
    {
        GCConnectionStatus_HAVE_SESSION = 0,
        GCConnectionStatus_GC_GOING_DOWN = 1,
        GCConnectionStatus_NO_SESSION = 2,
        GCConnectionStatus_NO_SESSION_IN_LOGON_QUEUE = 3,
        GCConnectionStatus_NO_STEAM = 4,
    }

    [ProtoContract()]
    public enum EGCItemMsg
    {
        k_EMsgGCBase = 1000,
        k_EMsgGCSetItemPosition = 1001,
        k_EMsgGCCraft = 1002,
        k_EMsgGCCraftResponse = 1003,
        k_EMsgGCDelete = 1004,
        k_EMsgGCVerifyCacheSubscription = 1005,
        k_EMsgGCNameItem = 1006,
        k_EMsgGCUnlockCrate_DEPRECATED = 1007,
        k_EMsgGCUnlockCrateResponse = 1008,
        k_EMsgGCPaintItem = 1009,
        k_EMsgGCPaintItemResponse = 1010,
        k_EMsgGCGoldenWrenchBroadcast = 1011,
        k_EMsgGCMOTDRequest = 1012,
        k_EMsgGCMOTDRequestResponse = 1013,
        k_EMsgGCAddItemToSocket_DEPRECATED = 1014,
        k_EMsgGCAddItemToSocketResponse_DEPRECATED = 1015,
        k_EMsgGCAddSocketToBaseItem_DEPRECATED = 1016,
        k_EMsgGCAddSocketToItem_DEPRECATED = 1017,
        k_EMsgGCAddSocketToItemResponse_DEPRECATED = 1018,
        k_EMsgGCNameBaseItem = 1019,
        k_EMsgGCNameBaseItemResponse = 1020,
        k_EMsgGCRemoveSocketItem_DEPRECATED = 1021,
        k_EMsgGCRemoveSocketItemResponse_DEPRECATED = 1022,
        k_EMsgGCCustomizeItemTexture = 1023,
        k_EMsgGCCustomizeItemTextureResponse = 1024,
        k_EMsgGCUseItemRequest = 1025,
        k_EMsgGCUseItemResponse = 1026,
        k_EMsgGCGiftedItems_DEPRECATED = 1027,
        k_EMsgGCRemoveItemName = 1030,
        k_EMsgGCRemoveItemPaint = 1031,
        k_EMsgGCGiftWrapItem = 1032,
        k_EMsgGCGiftWrapItemResponse = 1033,
        k_EMsgGCDeliverGift = 1034,
        k_EMsgGCDeliverGiftResponseGiver = 1035,
        k_EMsgGCDeliverGiftResponseReceiver = 1036,
        k_EMsgGCUnwrapGiftRequest = 1037,
        k_EMsgGCUnwrapGiftResponse = 1038,
        k_EMsgGCSetItemStyle = 1039,
        k_EMsgGCUsedClaimCodeItem = 1040,
        k_EMsgGCSortItems = 1041,
        k_EMsgGC_RevolvingLootList_DEPRECATED = 1042,
        k_EMsgGCLookupAccount = 1043,
        k_EMsgGCLookupAccountResponse = 1044,
        k_EMsgGCLookupAccountName = 1045,
        k_EMsgGCLookupAccountNameResponse = 1046,
        k_EMsgGCUpdateItemSchema = 1049,
        k_EMsgGCRemoveCustomTexture = 1051,
        k_EMsgGCRemoveCustomTextureResponse = 1052,
        k_EMsgGCRemoveMakersMark = 1053,
        k_EMsgGCRemoveMakersMarkResponse = 1054,
        k_EMsgGCRemoveUniqueCraftIndex = 1055,
        k_EMsgGCRemoveUniqueCraftIndexResponse = 1056,
        k_EMsgGCSaxxyBroadcast = 1057,
        k_EMsgGCBackpackSortFinished = 1058,
        k_EMsgGCCollectItem = 1061,
        k_EMsgGCItemAcknowledged__DEPRECATED = 1062,
        k_EMsgGC_ReportAbuse = 1065,
        k_EMsgGC_ReportAbuseResponse = 1066,
        k_EMsgGCNameItemNotification = 1068,
        k_EMsgGCApplyConsumableEffects = 1069,
        k_EMsgGCConsumableExhausted = 1070,
        k_EMsgGCShowItemsPickedUp = 1071,
        k_EMsgGCClientDisplayNotification = 1072,
        k_EMsgGCApplyStrangePart = 1073,
        k_EMsgGC_IncrementKillCountAttribute = 1074,
        k_EMsgGC_IncrementKillCountResponse = 1075,
        k_EMsgGCApplyPennantUpgrade = 1076,
        k_EMsgGCSetItemPositions = 1077,
        k_EMsgGCApplyEggEssence = 1078,
        k_EMsgGCNameEggEssenceResponse = 1079,
        k_EMsgGCPaintKitItem = 1080,
        k_EMsgGCPaintKitBaseItem = 1081,
        k_EMsgGCPaintKitItemResponse = 1082,
        k_EMsgGCGiftedItems = 1083,
        k_EMsgGCUnlockItemStyle = 1084,
        k_EMsgGCUnlockItemStyleResponse = 1085,
        k_EMsgGCApplySticker = 1086,
        k_EMsgGCItemAcknowledged = 1087,
        k_EMsgGCStatTrakSwap = 1088,
        k_EMsgGCUserTrackTimePlayedConsecutively = 1089,
        k_EMsgGCItemCustomizationNotification = 1090,
        k_EMsgGCModifyItemAttribute = 1091,
        k_EMsgGCCasketItemAdd = 1092,
        k_EMsgGCCasketItemExtract = 1093,
        k_EMsgGCCasketItemLoadContents = 1094,
        k_EMsgGCTradingBase = 1500,
        k_EMsgGCTrading_InitiateTradeRequest = 1501,
        k_EMsgGCTrading_InitiateTradeResponse = 1502,
        k_EMsgGCTrading_StartSession = 1503,
        k_EMsgGCTrading_SetItem = 1504,
        k_EMsgGCTrading_RemoveItem = 1505,
        k_EMsgGCTrading_UpdateTradeInfo = 1506,
        k_EMsgGCTrading_SetReadiness = 1507,
        k_EMsgGCTrading_ReadinessResponse = 1508,
        k_EMsgGCTrading_SessionClosed = 1509,
        k_EMsgGCTrading_CancelSession = 1510,
        k_EMsgGCTrading_TradeChatMsg = 1511,
        k_EMsgGCTrading_ConfirmOffer = 1512,
        k_EMsgGCTrading_TradeTypingChatMsg = 1513,
        k_EMsgGCServerBrowser_FavoriteServer = 1601,
        k_EMsgGCServerBrowser_BlacklistServer = 1602,
        k_EMsgGCServerRentalsBase = 1700,
        k_EMsgGCItemPreviewCheckStatus = 1701,
        k_EMsgGCItemPreviewStatusResponse = 1702,
        k_EMsgGCItemPreviewRequest = 1703,
        k_EMsgGCItemPreviewRequestResponse = 1704,
        k_EMsgGCItemPreviewExpire = 1705,
        k_EMsgGCItemPreviewExpireNotification = 1706,
        k_EMsgGCItemPreviewItemBoughtNotification = 1707,
        k_EMsgGCDev_NewItemRequest = 2001,
        k_EMsgGCDev_NewItemRequestResponse = 2002,
        k_EMsgGCDev_PaintKitDropItem = 2003,
        k_EMsgGCDev_SchemaReservationRequest = 2004,
        k_EMsgGCStoreGetUserData = 2500,
        k_EMsgGCStoreGetUserDataResponse = 2501,
        k_EMsgGCStorePurchaseInit_DEPRECATED = 2502,
        k_EMsgGCStorePurchaseInitResponse_DEPRECATED = 2503,
        k_EMsgGCStorePurchaseFinalize = 2504,
        k_EMsgGCStorePurchaseFinalizeResponse = 2505,
        k_EMsgGCStorePurchaseCancel = 2506,
        k_EMsgGCStorePurchaseCancelResponse = 2507,
        k_EMsgGCStorePurchaseQueryTxn = 2508,
        k_EMsgGCStorePurchaseQueryTxnResponse = 2509,
        k_EMsgGCStorePurchaseInit = 2510,
        k_EMsgGCStorePurchaseInitResponse = 2511,
        k_EMsgGCBannedWordListRequest = 2512,
        k_EMsgGCBannedWordListResponse = 2513,
        k_EMsgGCToGCBannedWordListBroadcast = 2514,
        k_EMsgGCToGCBannedWordListUpdated = 2515,
        k_EMsgGCToGCDirtySDOCache = 2516,
        k_EMsgGCToGCDirtyMultipleSDOCache = 2517,
        k_EMsgGCToGCUpdateSQLKeyValue = 2518,
        k_EMsgGCToGCIsTrustedServer = 2519,
        k_EMsgGCToGCIsTrustedServerResponse = 2520,
        k_EMsgGCToGCBroadcastConsoleCommand = 2521,
        k_EMsgGCServerVersionUpdated = 2522,
        k_EMsgGCToGCWebAPIAccountChanged = 2524,
        k_EMsgGCRequestAnnouncements = 2525,
        k_EMsgGCRequestAnnouncementsResponse = 2526,
        k_EMsgGCRequestPassportItemGrant = 2527,
        k_EMsgGCClientVersionUpdated = 2528,
        k_EMsgGCRecurringSubscriptionStatus = 2530,
        k_EMsgGCAdjustEquipSlotsManual = 2531,
        k_EMsgGCAdjustEquipSlotsShuffle = 2532,
        k_EMsgGCOpenCrate = 2534,
        k_EMsgGCAcknowledgeRentalExpiration = 2535,
        k_EMsgGCVolatileItemLoadContents = 2536,
    }

    [ProtoContract()]
    public enum EGCMsgResponse
    {
        k_EGCMsgResponseOK = 0,
        k_EGCMsgResponseDenied = 1,
        k_EGCMsgResponseServerError = 2,
        k_EGCMsgResponseTimeout = 3,
        k_EGCMsgResponseInvalid = 4,
        k_EGCMsgResponseNoMatch = 5,
        k_EGCMsgResponseUnknownError = 6,
        k_EGCMsgResponseNotLoggedOn = 7,
        k_EGCMsgFailedToCreate = 8,
        k_EGCMsgLimitExceeded = 9,
        k_EGCMsgCommitUnfinalized = 10,
    }

    [ProtoContract()]
    public enum EGCItemCustomizationNotification
    {
        k_EGCItemCustomizationNotification_NameItem = 1006,
        k_EGCItemCustomizationNotification_UnlockCrate = 1007,
        k_EGCItemCustomizationNotification_XRayItemReveal = 1008,
        k_EGCItemCustomizationNotification_XRayItemClaim = 1009,
        k_EGCItemCustomizationNotification_CasketTooFull = 1011,
        k_EGCItemCustomizationNotification_CasketContents = 1012,
        k_EGCItemCustomizationNotification_CasketAdded = 1013,
        k_EGCItemCustomizationNotification_CasketRemoved = 1014,
        k_EGCItemCustomizationNotification_CasketInvFull = 1015,
        k_EGCItemCustomizationNotification_NameBaseItem = 1019,
        k_EGCItemCustomizationNotification_RemoveItemName = 1030,
        k_EGCItemCustomizationNotification_RemoveSticker = 1053,
        k_EGCItemCustomizationNotification_ExtractSticker = 1054,
        k_EGCItemCustomizationNotification_EncapsulateSticker = 1055,
        k_EGCItemCustomizationNotification_ApplySticker = 1086,
        k_EGCItemCustomizationNotification_StatTrakSwap = 1088,
        k_EGCItemCustomizationNotification_RemovePatch = 1089,
        k_EGCItemCustomizationNotification_ApplyPatch = 1090,
        k_EGCItemCustomizationNotification_ApplyKeychain = 1091,
        k_EGCItemCustomizationNotification_RemoveKeychain = 1092,
        k_EGCItemCustomizationNotification_ActivateFanToken = 9178,
        k_EGCItemCustomizationNotification_ActivateOperationCoin = 9179,
        k_EGCItemCustomizationNotification_GraffitiUnseal = 9185,
        k_EGCItemCustomizationNotification_GenerateSouvenir = 9204,
        k_EGCItemCustomizationNotification_ClientRedeemMissionReward = 9209,
        k_EGCItemCustomizationNotification_ClientRedeemFreeReward = 9219,
        k_EGCItemCustomizationNotification_XpShopUseTicket = 9221,
        k_EGCItemCustomizationNotification_XpShopAckTracks = 9222,
    }

    [ProtoContract()]
    public enum EGCToGCMsg
    {
        k_EGCToGCMsgMasterAck = 150,
        k_EGCToGCMsgMasterAckResponse = 151,
        k_EGCToGCMsgRouted = 152,
        k_EGCToGCMsgRoutedReply = 153,
        k_EMsgUpdateSessionIP = 154,
        k_EMsgRequestSessionIP = 155,
        k_EMsgRequestSessionIPResponse = 156,

    }

    [ProtoContract()]
    public enum ECommunityItemClass
    {
        k_ECommunityItemClass_Invalid = 0,
        k_ECommunityItemClass_Badge = 1,
        k_ECommunityItemClass_GameCard = 2,
        k_ECommunityItemClass_ProfileBackground = 3,
        k_ECommunityItemClass_Emoticon = 4,
        k_ECommunityItemClass_BoosterPack = 5,
        k_ECommunityItemClass_Consumable = 6,
        k_ECommunityItemClass_GameGoo = 7,
        k_ECommunityItemClass_ProfileModifier = 8,
        k_ECommunityItemClass_Scene = 9,
        k_ECommunityItemClass_SalienItem = 10,
    }

    [ProtoContract()]
    public enum ECommunityItemAttribute
    {
        k_ECommunityItemAttribute_Invalid = 0,
        k_ECommunityItemAttribute_CardBorder = 1,
        k_ECommunityItemAttribute_Level = 2,
        k_ECommunityItemAttribute_IssueNumber = 3,
        k_ECommunityItemAttribute_TradableTime = 4,
        k_ECommunityItemAttribute_StorePackageID = 5,
        k_ECommunityItemAttribute_CommunityItemAppID = 6,
        k_ECommunityItemAttribute_CommunityItemType = 7,
        k_ECommunityItemAttribute_ProfileModiferEnabled = 8,
        k_ECommunityItemAttribute_ExpiryTime = 9,
    }
}
